-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 12:50:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema S2.01_N1Ex1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `S2.01_N1Ex1` ;

-- -----------------------------------------------------
-- Schema S2.01_N1Ex1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S2.01_N1Ex1` DEFAULT CHARACTER SET utf8 ;
USE `S2.01_N1Ex1` ;

-- -----------------------------------------------------
-- Table `S2.01_N1Ex1`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex1`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(100) NOT NULL,
  `Telephone` INT(15) NOT NULL,
  `FAX VARCHAR (20)` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex1`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex1`.`Brand` (
  `idBrand` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idBrand`),
  CONSTRAINT `fk_Brand_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `S2.01_N1Ex1`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Brand_Supplier1_idx` ON `S2.01_N1Ex1`.`Brand` (`Supplier_idSupplier` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex1`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex1`.`Glasses` (
  `idGlasses` INT NOT NULL,
  `Left glass graduation` FLOAT(5) NULL,
  `Right glass graduation` FLOAT(5) NULL,
  `Mount type` VARCHAR(20) NOT NULL,
  `Color` VARCHAR(10) NOT NULL,
  `Left glass color` VARCHAR(20) NOT NULL,
  `Right glass color` VARCHAR(20) NOT NULL,
  `Price` INT(5) NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  CONSTRAINT `fk_Glasses_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `S2.01_N1Ex1`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Glasses_Brand1_idx` ON `S2.01_N1Ex1`.`Glasses` (`Brand_idBrand` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex1`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex1`.`Clients` (
  `idClients` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Postal code` INT(8) NOT NULL,
  `Telephone` INT(12) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `Registration date` DATE NOT NULL,
  `Employee` VARCHAR(45) NOT NULL,
  `Recommended customer_idClients` INT NULL,
  PRIMARY KEY (`idClients`),
  CONSTRAINT `fk_Clients_Clients1`
    FOREIGN KEY (`Recommended customer_idClients`)
    REFERENCES `S2.01_N1Ex1`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Clients_Clients1_idx` ON `S2.01_N1Ex1`.`Clients` (`Recommended customer_idClients` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex1`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex1`.`Employee` (
  `idEmployee` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(100) NOT NULL,
  `Telephone` INT(15) NOT NULL,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex1`.`Buy/Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex1`.`Buy/Sale` (
  `idBuy/Sale` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  `Glasses_idGlasses` INT NOT NULL,
  PRIMARY KEY (`idBuy/Sale`),
  CONSTRAINT `fk_Buy/Sale_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `S2.01_N1Ex1`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Buy/Sale_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `S2.01_N1Ex1`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Buy/Sale_Glasses1`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `S2.01_N1Ex1`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Buy/Sale_Clients1_idx` ON `S2.01_N1Ex1`.`Buy/Sale` (`Clients_idClients` ASC) VISIBLE;

CREATE INDEX `fk_Buy/Sale_Employee1_idx` ON `S2.01_N1Ex1`.`Buy/Sale` (`Employee_idEmployee` ASC) VISIBLE;

CREATE INDEX `fk_Buy/Sale_Glasses1_idx` ON `S2.01_N1Ex1`.`Buy/Sale` (`Glasses_idGlasses` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
