-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 21:11:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema S2.01_N3Ex1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `S2.01_N3Ex1` ;

-- -----------------------------------------------------
-- Schema S2.01_N3Ex1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S2.01_N3Ex1` DEFAULT CHARACTER SET utf8 ;
USE `S2.01_N3Ex1` ;

-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Subscription` (
  `idSubscripcion` INT NOT NULL,
  `start date` DATE NOT NULL,
  `renovation` DATE NOT NULL,
  PRIMARY KEY (`idSubscripcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`User` (
  `idUsuario` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `psotal code` INT(5) NOT NULL,
  `birthday` DATE NOT NULL,
  `Subscription_idSubscripcion` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_User_Subscription1`
    FOREIGN KEY (`Subscription_idSubscripcion`)
    REFERENCES `S2.01_N3Ex1`.`Subscription` (`idSubscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_User_Subscription1_idx` ON `S2.01_N3Ex1`.`User` (`Subscription_idSubscripcion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Card` (
  `idTarjeta` INT NOT NULL,
  `card number` INT NOT NULL,
  `date of expiry` DATE NOT NULL,
  `CVV` INT(5) NOT NULL,
  PRIMARY KEY (`idTarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Pay` (
  `idPago` INT NOT NULL,
  `date` DATE NOT NULL,
  `total price` FLOAT NOT NULL,
  `Subscription_idSubscripcion` INT NOT NULL,
  `Card_idTarjeta` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  CONSTRAINT `fk_Pay_Subscription1`
    FOREIGN KEY (`Subscription_idSubscripcion`)
    REFERENCES `S2.01_N3Ex1`.`Subscription` (`idSubscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pay_Card1`
    FOREIGN KEY (`Card_idTarjeta`)
    REFERENCES `S2.01_N3Ex1`.`Card` (`idTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pay_Subscription1_idx` ON `S2.01_N3Ex1`.`Pay` (`Subscription_idSubscripcion` ASC) VISIBLE;

CREATE INDEX `fk_Pay_Card1_idx` ON `S2.01_N3Ex1`.`Pay` (`Card_idTarjeta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Paypal` (
  `idPaypal` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `Pay_idPago` INT NOT NULL,
  PRIMARY KEY (`idPaypal`),
  CONSTRAINT `fk_Paypal_Pay1`
    FOREIGN KEY (`Pay_idPago`)
    REFERENCES `S2.01_N3Ex1`.`Pay` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paypal_Pay1_idx` ON `S2.01_N3Ex1`.`Paypal` (`Pay_idPago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Playlist` (
  `idPlaylists` INT NOT NULL,
  `tittle` VARCHAR(45) NOT NULL,
  `song` VARCHAR(45) NOT NULL,
  `creation date` DATE NOT NULL,
  PRIMARY KEY (`idPlaylists`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Musical genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Musical genre` (
  `idGenero musical` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero musical`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Artist` (
  `idArtista` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `Musical genre_idGenero musical` INT NOT NULL,
  PRIMARY KEY (`idArtista`),
  CONSTRAINT `fk_Artist_Musical genre1`
    FOREIGN KEY (`Musical genre_idGenero musical`)
    REFERENCES `S2.01_N3Ex1`.`Musical genre` (`idGenero musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Artist_Musical genre1_idx` ON `S2.01_N3Ex1`.`Artist` (`Musical genre_idGenero musical` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Album` (
  `idAlbum` INT NOT NULL,
  `tittle` VARCHAR(45) NOT NULL,
  `release year` INT(4) NOT NULL,
  `cover image` VARCHAR(45) NOT NULL,
  `Artist_idArtista` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  CONSTRAINT `fk_Album_Artist1`
    FOREIGN KEY (`Artist_idArtista`)
    REFERENCES `S2.01_N3Ex1`.`Artist` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Album_Artist1_idx` ON `S2.01_N3Ex1`.`Album` (`Artist_idArtista` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Song` (
  `idCancion` INT NOT NULL,
  `tittle` VARCHAR(45) NOT NULL,
  `duration` FLOAT NOT NULL,
  `reproductions` INT NOT NULL,
  `Album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idCancion`, `Album_idAlbum`),
  CONSTRAINT `fk_Song_Album1`
    FOREIGN KEY (`Album_idAlbum`)
    REFERENCES `S2.01_N3Ex1`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Song_Album1_idx` ON `S2.01_N3Ex1`.`Song` (`Album_idAlbum` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Favorite song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Favorite song` (
  `idCancion favorita` INT NOT NULL,
  `Song_idCancion` INT NOT NULL,
  `User_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCancion favorita`),
  CONSTRAINT `fk_Favorite song_Song1`
    FOREIGN KEY (`Song_idCancion`)
    REFERENCES `S2.01_N3Ex1`.`Song` (`idCancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorite song_User1`
    FOREIGN KEY (`User_idUsuario`)
    REFERENCES `S2.01_N3Ex1`.`User` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Favorite song_Song1_idx` ON `S2.01_N3Ex1`.`Favorite song` (`Song_idCancion` ASC) VISIBLE;

CREATE INDEX `fk_Favorite song_User1_idx` ON `S2.01_N3Ex1`.`Favorite song` (`User_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Favorite album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Favorite album` (
  `idAlbum favorito` INT NOT NULL,
  `Album_idAlbum` INT NOT NULL,
  `User_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAlbum favorito`),
  CONSTRAINT `fk_Favorite album_Album1`
    FOREIGN KEY (`Album_idAlbum`)
    REFERENCES `S2.01_N3Ex1`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorite album_User1`
    FOREIGN KEY (`User_idUsuario`)
    REFERENCES `S2.01_N3Ex1`.`User` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Favorite album_Album1_idx` ON `S2.01_N3Ex1`.`Favorite album` (`Album_idAlbum` ASC) VISIBLE;

CREATE INDEX `fk_Favorite album_User1_idx` ON `S2.01_N3Ex1`.`Favorite album` (`User_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Favorite artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Favorite artist` (
  `idArtista favorito` INT NOT NULL,
  `Artist_idArtista` INT NOT NULL,
  `User_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idArtista favorito`),
  CONSTRAINT `fk_Favorite artist_Artist1`
    FOREIGN KEY (`Artist_idArtista`)
    REFERENCES `S2.01_N3Ex1`.`Artist` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorite artist_User1`
    FOREIGN KEY (`User_idUsuario`)
    REFERENCES `S2.01_N3Ex1`.`User` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Favorite artist_Artist1_idx` ON `S2.01_N3Ex1`.`Favorite artist` (`Artist_idArtista` ASC) VISIBLE;

CREATE INDEX `fk_Favorite artist_User1_idx` ON `S2.01_N3Ex1`.`Favorite artist` (`User_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Deleted playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Deleted playlist` (
  `idPlaylist eliminada` INT NOT NULL,
  `date` DATE NOT NULL,
  `Playlist_idPlaylists` INT NOT NULL,
  `User_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPlaylist eliminada`),
  CONSTRAINT `fk_Deleted playlist_Playlist`
    FOREIGN KEY (`Playlist_idPlaylists`)
    REFERENCES `S2.01_N3Ex1`.`Playlist` (`idPlaylists`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deleted playlist_User1`
    FOREIGN KEY (`User_idUsuario`)
    REFERENCES `S2.01_N3Ex1`.`User` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Deleted playlist_Playlist_idx` ON `S2.01_N3Ex1`.`Deleted playlist` (`Playlist_idPlaylists` ASC) VISIBLE;

CREATE INDEX `fk_Deleted playlist_User1_idx` ON `S2.01_N3Ex1`.`Deleted playlist` (`User_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`Song_has_Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`Song_has_Playlist` (
  `Song_idCancion` INT NOT NULL,
  `Playlist_idPlaylists` INT NOT NULL,
  PRIMARY KEY (`Song_idCancion`, `Playlist_idPlaylists`),
  CONSTRAINT `fk_Song_has_Playlist_Song1`
    FOREIGN KEY (`Song_idCancion`)
    REFERENCES `S2.01_N3Ex1`.`Song` (`idCancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Song_has_Playlist_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylists`)
    REFERENCES `S2.01_N3Ex1`.`Playlist` (`idPlaylists`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Song_has_Playlist_Playlist1_idx` ON `S2.01_N3Ex1`.`Song_has_Playlist` (`Playlist_idPlaylists` ASC) VISIBLE;

CREATE INDEX `fk_Song_has_Playlist_Song1_idx` ON `S2.01_N3Ex1`.`Song_has_Playlist` (`Song_idCancion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N3Ex1`.`User_has_Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N3Ex1`.`User_has_Playlist` (
  `User_idUsuario` INT NOT NULL,
  `Playlist_idPlaylists` INT NOT NULL,
  PRIMARY KEY (`User_idUsuario`, `Playlist_idPlaylists`),
  CONSTRAINT `fk_User_has_Playlist_User1`
    FOREIGN KEY (`User_idUsuario`)
    REFERENCES `S2.01_N3Ex1`.`User` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Playlist_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylists`)
    REFERENCES `S2.01_N3Ex1`.`Playlist` (`idPlaylists`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_User_has_Playlist_Playlist1_idx` ON `S2.01_N3Ex1`.`User_has_Playlist` (`Playlist_idPlaylists` ASC) VISIBLE;

CREATE INDEX `fk_User_has_Playlist_User1_idx` ON `S2.01_N3Ex1`.`User_has_Playlist` (`User_idUsuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
