-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 09:20:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema S2.01_N1Ex2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `S2.01_N1Ex2` ;

-- -----------------------------------------------------
-- Schema S2.01_N1Ex2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S2.01_N1Ex2` DEFAULT CHARACTER SET utf8 ;
USE `S2.01_N1Ex2` ;

-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Province` (
  `idProvince` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvince`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Locality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Locality` (
  `idLocality` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Postal code` INT NOT NULL,
  `Province_idProvince` INT NOT NULL,
  PRIMARY KEY (`idLocality`),
  CONSTRAINT `fk_Locality_Province1`
    FOREIGN KEY (`Province_idProvince`)
    REFERENCES `S2.01_N1Ex2`.`Province` (`idProvince`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Locality_Province1_idx` ON `S2.01_N1Ex2`.`Locality` (`Province_idProvince` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Client` (
  `idClient` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(100) NOT NULL,
  `Telephone` INT(12) NOT NULL,
  `Locality_idLocality` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  CONSTRAINT `fk_Client_Locality1`
    FOREIGN KEY (`Locality_idLocality`)
    REFERENCES `S2.01_N1Ex2`.`Locality` (`idLocality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Client_Locality1_idx` ON `S2.01_N1Ex2`.`Client` (`Locality_idLocality` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Store` (
  `idStore` INT NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `Locality_idLocality` INT NOT NULL,
  PRIMARY KEY (`idStore`),
  CONSTRAINT `fk_Store_Locality1`
    FOREIGN KEY (`Locality_idLocality`)
    REFERENCES `S2.01_N1Ex2`.`Locality` (`idLocality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Store_Locality1_idx` ON `S2.01_N1Ex2`.`Store` (`Locality_idLocality` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Employee` (
  `idEmployee` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(12) NOT NULL,
  `Telephone` INT(45) NOT NULL,
  `Store_idStore` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  CONSTRAINT `fk_Employee_Store1`
    FOREIGN KEY (`Store_idStore`)
    REFERENCES `S2.01_N1Ex2`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Employee_Store1_idx` ON `S2.01_N1Ex2`.`Employee` (`Store_idStore` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Order` (
  `idOrder` INT NOT NULL,
  `Data/Hour` DATETIME(1) NOT NULL,
  `Order type` ENUM('delivery', 'take away') NOT NULL,
  `Quantity` INT(2) NOT NULL,
  `Total price` INT(4) NOT NULL,
  `Store_idStore` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `S2.01_N1Ex2`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `S2.01_N1Ex2`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Order_Employee1_idx` ON `S2.01_N1Ex2`.`Order` (`Employee_idEmployee` ASC) VISIBLE;

CREATE INDEX `fk_Order_Client1_idx` ON `S2.01_N1Ex2`.`Order` (`Client_idClient` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Category` (
  `idCategory` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Pizza` (
  `idPizza` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Image` VARCHAR(45) NOT NULL,
  `Price` INT(5) NOT NULL,
  `Order_idOrder` INT NOT NULL,
  `Category_idCategory` INT NOT NULL,
  PRIMARY KEY (`idPizza`),
  CONSTRAINT `fk_Pizza_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `S2.01_N1Ex2`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `S2.01_N1Ex2`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pizza_Order1_idx` ON `S2.01_N1Ex2`.`Pizza` (`Order_idOrder` ASC) VISIBLE;

CREATE INDEX `fk_Pizza_Category1_idx` ON `S2.01_N1Ex2`.`Pizza` (`Category_idCategory` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Hamburguer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Hamburguer` (
  `idHamburguer` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Image` VARCHAR(45) NOT NULL,
  `Price` INT(5) NOT NULL,
  `Order_idOrder` INT NOT NULL,
  PRIMARY KEY (`idHamburguer`),
  CONSTRAINT `fk_Hamburguer_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `S2.01_N1Ex2`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Hamburguer_Order1_idx` ON `S2.01_N1Ex2`.`Hamburguer` (`Order_idOrder` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Drink` (
  `idDrink` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Image` VARCHAR(45) NOT NULL,
  `Price` INT(5) NOT NULL,
  `Order_idOrder` INT NOT NULL,
  PRIMARY KEY (`idDrink`),
  CONSTRAINT `fk_Drink_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `S2.01_N1Ex2`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Drink_Order1_idx` ON `S2.01_N1Ex2`.`Drink` (`Order_idOrder` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
