-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 21:08:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema S2.01_N1Ex2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `S2.01_N1Ex2` ;

-- -----------------------------------------------------
-- Schema S2.01_N1Ex2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S2.01_N1Ex2` DEFAULT CHARACTER SET utf8mb4 ;
USE `S2.01_N1Ex2` ;

-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Channel` (
  `idChannel` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Creation date` DATE NOT NULL,
  PRIMARY KEY (`idChannel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`User` (
  `idUser` INT NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Birthdate` DATE NOT NULL,
  `Sex` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Post collection` VARCHAR(45) NOT NULL,
  `Channel_idChannel` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_User_Channel1`
    FOREIGN KEY (`Channel_idChannel`)
    REFERENCES `S2.01_N1Ex2`.`Channel` (`idChannel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_User_Channel1_idx` ON `S2.01_N1Ex2`.`User` (`Channel_idChannel` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Video` (
  `idVideo` INT NOT NULL,
  `Tittle` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Size` INT NOT NULL,
  `File name` VARCHAR(45) NOT NULL,
  `Duration` INT NOT NULL,
  `Thumbnail` VARCHAR(45) NOT NULL,
  `Views` INT NOT NULL,
  `Visibility` ENUM('public', 'hidden', 'private') NOT NULL,
  `Creation date` DATETIME(1) NOT NULL,
  `Channel_idChannel` INT NOT NULL,
  PRIMARY KEY (`idVideo`),
  CONSTRAINT `fk_Video_Channel1`
    FOREIGN KEY (`Channel_idChannel`)
    REFERENCES `S2.01_N1Ex2`.`Channel` (`idChannel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Video_Channel1_idx` ON `S2.01_N1Ex2`.`Video` (`Channel_idChannel` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Playlist` (
  `idPlaylist` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Creation date` DATE NOT NULL,
  `Visibility` ENUM('public', 'private') NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPlaylist`),
  CONSTRAINT `fk_Playlist_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `S2.01_N1Ex2`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Playlist_User1_idx` ON `S2.01_N1Ex2`.`Playlist` (`User_idUser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Commentary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Commentary` (
  `idCommentary` INT NOT NULL,
  `Text` VARCHAR(45) NOT NULL,
  `Creation date` DATETIME(1) NOT NULL,
  `Video_idVideo` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idCommentary`),
  CONSTRAINT `fk_Commentary_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `S2.01_N1Ex2`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentary_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `S2.01_N1Ex2`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Commentary_Video1_idx` ON `S2.01_N1Ex2`.`Commentary` (`Video_idVideo` ASC) VISIBLE;

CREATE INDEX `fk_Commentary_User1_idx` ON `S2.01_N1Ex2`.`Commentary` (`User_idUser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Tag` (
  `idTag` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Video_idVideo` INT NOT NULL,
  PRIMARY KEY (`idTag`),
  CONSTRAINT `fk_Tag_Video`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `S2.01_N1Ex2`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tag_Video_idx` ON `S2.01_N1Ex2`.`Tag` (`Video_idVideo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Like/dislike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Like/dislike` (
  `idLike/dislike` INT NOT NULL,
  `Creation date` DATETIME(1) NOT NULL,
  `Video_idVideo` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Commentary_idCommentary` INT NOT NULL,
  PRIMARY KEY (`idLike/dislike`),
  CONSTRAINT `fk_Like/dislike_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `S2.01_N1Ex2`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like/dislike_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `S2.01_N1Ex2`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like/dislike_Commentary1`
    FOREIGN KEY (`Commentary_idCommentary`)
    REFERENCES `S2.01_N1Ex2`.`Commentary` (`idCommentary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Like/dislike_Video1_idx` ON `S2.01_N1Ex2`.`Like/dislike` (`Video_idVideo` ASC) VISIBLE;

CREATE INDEX `fk_Like/dislike_User1_idx` ON `S2.01_N1Ex2`.`Like/dislike` (`User_idUser` ASC) VISIBLE;

CREATE INDEX `fk_Like/dislike_Commentary1_idx` ON `S2.01_N1Ex2`.`Like/dislike` (`Commentary_idCommentary` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Suscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Suscription` (
  `idSuscription` INT NOT NULL,
  `Suscription date` DATETIME(1) NOT NULL,
  `User_idUser` INT NOT NULL,
  `Channel_idChannel` INT NOT NULL,
  PRIMARY KEY (`idSuscription`),
  CONSTRAINT `fk_Suscription_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `S2.01_N1Ex2`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suscription_Channel1`
    FOREIGN KEY (`Channel_idChannel`)
    REFERENCES `S2.01_N1Ex2`.`Channel` (`idChannel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Suscription_User1_idx` ON `S2.01_N1Ex2`.`Suscription` (`User_idUser` ASC) VISIBLE;

CREATE INDEX `fk_Suscription_Channel1_idx` ON `S2.01_N1Ex2`.`Suscription` (`Channel_idChannel` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `S2.01_N1Ex2`.`Playlist_has_Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2.01_N1Ex2`.`Playlist_has_Video` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Video_idVideo` INT NOT NULL,
  PRIMARY KEY (`Playlist_idPlaylist`, `Video_idVideo`),
  CONSTRAINT `fk_Playlist_has_Video_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `S2.01_N1Ex2`.`Playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_has_Video_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `S2.01_N1Ex2`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Playlist_has_Video_Video1_idx` ON `S2.01_N1Ex2`.`Playlist_has_Video` (`Video_idVideo` ASC) VISIBLE;

CREATE INDEX `fk_Playlist_has_Video_Playlist1_idx` ON `S2.01_N1Ex2`.`Playlist_has_Video` (`Playlist_idPlaylist` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
